name: SafehealthPush
targets:
  SafehealthPush:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [SafehealthPush]
    info:
      path: ./Info.plist
      version: 0.1.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
      - carthage: AnyCodable
  Test:
    type: Test
    platform: iOS
    deploymentTarget: "9.0"
    sources: [Tests]
    info:
      path: ./Info.plist
      version: 1.0.0
    scheme: {}
    dependencies:
      - carthage: Nuitee
